from django.db import models

class StudentPerformance(models.Model):
    gender = models.CharField(max_length=32)
    race_ethnicity = models.CharField(max_length=50)
    parental_level_of_education =  models.CharField(max_length=50)
    lunch = models.CharField(max_length=32)
    test_preparation_course = models.CharField(max_length=50)
    reading_score = models.IntegerField()
    math_score = models.IntegerField()

class Titanic(models.Model):
    Pclass = models.IntegerField()
    Sex = models.CharField(max_length=32)
    Age = models.IntegerField()
    SibSp = models.IntegerField()
    Parch = models.IntegerField()
    Fare = models.FloatField()
    SibParch = models.IntegerField()
    Embarked = models.CharField(max_length=32)

class House(models.Model):
    GrLivArea = models.IntegerField()
    YearBuilt = models.IntegerField()
    GarageCars = models.IntegerField()
    TotalBsmtSF = models.IntegerField()
    FullBath = models.IntegerField()
    OverallQual = models.IntegerField()
    Neighborhood = models.CharField(max_length=50)

class Bank(models.Model):
    person_age = models.IntegerField()
    person_gender = models.CharField(max_length=32)
    person_education = models.CharField(max_length=32)
    person_income = models.IntegerField()
    person_emp_exp = models.IntegerField()
    person_home_ownership = models.CharField(max_length=32)
    loan_amnt = models.IntegerField()
    loan_intent = models.CharField(max_length=32)
    loan_int_rate = models.FloatField()
    loan_percent_income = models.FloatField()
    cb_person_cred_hist_length = models.IntegerField()
    credit_score = models.IntegerField()
    previous_loan_defaults_on_file = models.CharField(max_length=32)

class Diabetes(models.Model):
    Pregnancies = models.IntegerField()
    Glucose = models.IntegerField()
    BloodPressure = models.IntegerField()
    SkinThickness = models.IntegerField()
    Insulin = models.IntegerField()
    BMI = models.FloatField()
    DiabetesPedigreeFunction = models.FloatField()
    Age = models.IntegerField()

class Avocado(models.Model):
    firmness = models.FloatField()
    hue = models.IntegerField()
    saturation = models.IntegerField()
    brightness = models.IntegerField()
    sound_db = models.IntegerField()
    weight_g = models.IntegerField()
    size_cm3 = models.IntegerField()
    color_category = models.CharField(max_length=32)

class Mushroom(models.Model):
    cap_shape = models.CharField(max_length=32)
    cap_surface = models.CharField(max_length=32)
    cap_color = models.CharField(max_length=32)
    bruises = models.CharField(max_length=32)
    odor = models.CharField(max_length=32)
    gill_attachment = models.CharField(max_length=32)
    gill_spacing = models.CharField(max_length=32)
    gill_size = models.CharField(max_length=32)
    gill_color = models.CharField(max_length=32)
    stalk_shape = models.CharField(max_length=32)
    stalk_root = models.CharField(max_length=32)
    stalk_surface_above_ring = models.CharField(max_length=32)
    stalk_surface_below_ring = models.CharField(max_length=32)
    stalk_color_above_ring = models.CharField(max_length=32)
    stalk_color_below_ring = models.CharField(max_length=32)
    veil_color = models.CharField(max_length=32)
    veil_type = models.CharField(max_length=32)
    ring_number = models.CharField(max_length=32)
    ring_type = models.CharField(max_length=32)
    spore_print_color = models.CharField(max_length=32)
    population = models.CharField(max_length=32)
    habitat = models.CharField(max_length=32)

class Telecom(models.Model):
        gender = models.CharField(max_length=32)
        SeniorCitizen = models.IntegerField()
        Partner = models.CharField(max_length=32)
        Dependents = models.CharField(max_length=32)
        tenure = models.IntegerField()
        PhoneService = models.CharField(max_length=32)
        MultipleLines = models.CharField(max_length=32)
        InternetService = models.CharField(max_length=32)
        OnlineSecurity = models.CharField(max_length=32)
        OnlineBackup = models.CharField(max_length=32)
        DeviceProtection = models.CharField(max_length=32)
        TechSupport = models.CharField(max_length=32)
        StreamingTV = models.CharField(max_length=32)
        StreamingMovies = models.CharField(max_length=32)
        Contract = models.CharField(max_length=32)
        PaperlessBilling = models.CharField(max_length=32)
        PaymentMethod = models.CharField(max_length=32)
        MonthlyCharges = models.FloatField()
        TotalCharges = models.FloatField()
