# Generated by Django 5.2.9 on 2026-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_projects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField()),
                ('Num_Ratings', models.IntegerField()),
                ('RAM', models.IntegerField()),
                ('ROM', models.IntegerField()),
                ('Back_Cam', models.IntegerField()),
                ('Front_Cam', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('Processor', models.CharField(max_length=64)),
                ('Scrap_Date', models.CharField(max_length=64)),
            ],
        ),
    ]
